import React from 'react';
import { storiesOf } from '@storybook/react';
import Emoji from './Emoji';

storiesOf('components|Emoji', module)
    .add('⏰', () => <Emoji value="⏰" width="50" height="50" />)
    .add('✔️', () => <Emoji value="✔️" width="50" height="50" />)
    .add('🚧', () => <Emoji value="🚧" width="50" height="50" />)
    .add('🔄', () => <Emoji value="🔄" width="50" height="50" />)
    .add('🏝', () => <Emoji value="🏝" width="50" height="50" />)
    .add('😥', () => <Emoji value="😥" width="50" height="50" />)
    .add('👀', () => <Emoji value="👀" width="50" height="50" />)
    .add('🔥', () => <Emoji value="🔥" width="50" height="50" />)
    .add('😅', () => <Emoji value="😅" width="50" height="50" />)
    .add('😃', () => <Emoji value="😃" width="50" height="50" />)
    .add('🤔', () => <Emoji value="🤔" width="50" height="50" />)
    .add('⌛️', () => <Emoji value="⌛️" width="50" height="50" />)
    .add('💸', () => <Emoji value="💸" width="50" height="50" />)
    .add('⛔️', () => <Emoji value="⛔️" width="50" height="50" />)
    .add('🚫', () => <Emoji value="🚫" width="50" height="50" />)
    .add('😍', () => <Emoji value="😍" width="50" height="50" />)
    .add('💦', () => <Emoji value="💦" width="50" height="50" />)
    .add('👍', () => <Emoji value="👍" width="50" height="50" />)
    .add('👋', () => <Emoji value="👋" width="50" height="50" />)
    .add('😩', () => <Emoji value="😩" width="50" height="50" />)
    .add('🥱', () => <Emoji value="🥱" width="50" height="50" />)
    .add('🔴', () => <Emoji value="🔴" width="50" height="50" />)
    .add('🔵', () => <Emoji value="🔵" width="50" height="50" />)
    .add('📈', () => <Emoji value="📈" width="50" height="50" />)
    .add('😞', () => <Emoji value="😞" width="50" height="50" />)
    .add('😉', () => <Emoji value="😉" width="50" height="50" />)
    .add('🚀', () => <Emoji value="🚀" width="50" height="50" />)
    .add('✅', () => <Emoji value="✅" width="50" height="50" />)
    .add('🎉', () => <Emoji value="🎉" width="50" height="50" />);